[package]
name = "bare-metal-evm-keccak"
version = "0.3.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Pure Rust Keccak-256 hash function implementation for #![no_std] environments"
keywords = ["keccak", "keccak256", "sha3", "hash", "no-std"]
categories = ["no-std", "cryptography"]
publish = ["crates-io", "github"]

[dev-dependencies]
hex.workspace = true
